### Je höher die Bewertung von „hoch/laut/abwechslungsreich/“, desto höher die Bewertung von „gewagt/temperamentvoll/unsensibel/modern/unaufrichtig“
H8: Je höher die Bewertung von „tief/leise/monoton/“, desto höher die Bewertung von „bodenständig/ruhig/einfühlsam/traditionell/aufrichtig“m

# Cramer's V

In [1]:
import pandas as pd 
import os

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import chi2_contingency

/Users/lilimatic/opt/anaconda3/lib/python3.8/site-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
path = 'data_perzeptionstest-vocal-branding_2024-02-10_11-56.csv'

df = pd.read_csv(path,sep=';',encoding='latin-1')

df =df.drop(columns=['CASE','SERIAL','REF','QUESTNNR','MODE','MAILSENT','LASTDATA','STARTED']+['TIME00'+str(x) for x in range(1,10)]+['TIME0'+str(x) for x in range(10,18)])

df = df.dropna()

spalten = []

for x in df.loc[0]:
    spalten.append(x)
    
#df.drop(df.index[0])

df.columns = spalten

df = df.reset_index()

df = df.drop(df.index[0])

In [3]:
import os

In [4]:
os.getcwd()

'/Users/lilimatic/constanze'

In [5]:
sprecher = []

for x in range(1,8):
    for y in range(1,3):
        sprecher.append(f'S{x}.{y}')

In [6]:
for s in sprecher:
    print(f'Sprecher {s}')
    A1 = f'Polaritätsprofil {s}: leise/laut'
    B1 = [f'Polaritätsprofil {s}: aufrichtig/unaufrichtig',f'Polaritätsprofil {s}: modern/traditionell',
     f'Polaritätsprofil {s}: gewagt/bodenständig', f'Polaritätsprofil {s}: ruhig/temperamentvoll',f'Polaritätsprofil {s}: einfühlsam/unsensibel'] 
    for i in B1:
        contingency = pd.crosstab(pd.to_numeric(df[A1]),pd.to_numeric(df[i]), margins=True)
        #display(contingency)
        #name = 'Tabelle_'+A1+'_'+i
        #contingency.to_csv(./name+'.csv')
        rel = round(pd.crosstab(df[A1],df[i],normalize='all',margins=True)*100,2)
        display(rel)

Sprecher S1.1

Polaritätsprofil S1.1: aufrichtig/unaufrichtig,1,2,3,4,5,All
Polaritätsprofil S1.1: leise/laut,,,,,,
2,0.00,1.72,1.72,3.45,0.00,6.90
3,5.17,29.31,15.52,6.90,0.00,56.90
4,3.45,12.07,8.62,1.72,3.45,29.31
5,1.72,1.72,3.45,0.00,0.00,6.90
All,10.34,44.83,29.31,12.07,3.45,100.00

Polaritätsprofil S1.1: modern/traditionell,1,2,3,4,5,All
Polaritätsprofil S1.1: leise/laut,,,,,,
2,1.72,1.72,1.72,1.72,0.00,6.90
3,15.52,22.41,10.34,5.17,3.45,56.90
4,8.62,10.34,5.17,5.17,0.00,29.31
5,5.17,1.72,0.00,0.00,0.00,6.90
All,31.03,36.21,17.24,12.07,3.45,100.00

Polaritätsprofil S1.1: gewagt/bodenständig     2      3      4      5     All
Polaritätsprofil S1.1: leise/laut
2                                           0.00   5.17   1.72   0.00    6.90
3                                           5.17  13.79  25.86  12.07   56.90
4                                           1.72   6.90  15.52   5.17   29.31
5                                           1.72   0.00   1.72   3.45    6.90
All                                         8.62  25.86  44.83  20.69  100.00

Polaritätsprofil S1.1: ruhig/temperamentvoll,1,2,3,4,5,All
Polaritätsprofil S1.1: leise/laut,,,,,,
2,1.72,3.45,1.72,0.00,0.00,6.90
3,3.45,18.97,15.52,18.97,0.00,56.90
4,0.00,12.07,10.34,5.17,1.72,29.31
5,1.72,0.00,3.45,0.00,1.72,6.90
All,6.90,34.48,31.03,24.14,3.45,100.00

Polaritätsprofil S1.1: einfühlsam/unsensibel,1,2,3,4,5,All
Polaritätsprofil S1.1: leise/laut,,,,,,
2,0.00,3.45,3.45,0.00,0.00,6.90
3,5.17,32.76,12.07,5.17,1.72,56.90
4,1.72,17.24,6.90,3.45,0.00,29.31
5,0.00,3.45,1.72,0.00,1.72,6.90
All,6.90,56.90,24.14,8.62,3.45,100.00

Sprecher S1.2

Polaritätsprofil S1.2: aufrichtig/unaufrichtig,1,2,3,4,5,All
Polaritätsprofil S1.2: leise/laut,,,,,,
2,0.00,0.00,1.72,3.45,0.00,5.17
3,0.00,3.45,5.17,8.62,6.90,24.14
4,1.72,5.17,12.07,25.86,6.90,51.72
5,1.72,0.00,3.45,3.45,10.34,18.97
All,3.45,8.62,22.41,41.38,24.14,100.00

Polaritätsprofil S1.2: modern/traditionell,1,2,3,4,5,All
Polaritätsprofil S1.2: leise/laut,,,,,,
2,1.72,1.72,1.72,0.00,0.00,5.17
3,3.45,8.62,8.62,1.72,1.72,24.14
4,5.17,24.14,15.52,6.90,0.00,51.72
5,8.62,5.17,5.17,0.00,0.00,18.97
All,18.97,39.66,31.03,8.62,1.72,100.00

Polaritätsprofil S1.2: gewagt/bodenständig,1,2,3,4,5,All
Polaritätsprofil S1.2: leise/laut,,,,,,
2,0.00,3.45,0.00,1.72,0.00,5.17
3,1.72,10.34,6.90,3.45,1.72,24.14
4,6.90,22.41,17.24,5.17,0.00,51.72
5,10.34,5.17,1.72,0.00,1.72,18.97
All,18.97,41.38,25.86,10.34,3.45,100.00

Polaritätsprofil S1.2: ruhig/temperamentvoll,1,2,3,4,5,All
Polaritätsprofil S1.2: leise/laut,,,,,,
2,0.00,0.00,1.72,3.45,0.00,5.17
3,1.72,0.00,6.90,13.79,1.72,24.14
4,0.00,3.45,12.07,31.03,5.17,51.72
5,0.00,0.00,1.72,8.62,8.62,18.97
All,1.72,3.45,22.41,56.90,15.52,100.00

Polaritätsprofil S1.2: einfühlsam/unsensibel      3      4      5     All
Polaritätsprofil S1.2: leise/laut
2                                              0.00   3.45   1.72    5.17
3                                              8.62  10.34   5.17   24.14
4                                              6.90  27.59  17.24   51.72
5                                              0.00   5.17  13.79   18.97
All                                           15.52  46.55  37.93  100.00

Sprecher S2.1

Polaritätsprofil S2.1: aufrichtig/unaufrichtig,1,2,3,4,5,All
Polaritätsprofil S2.1: leise/laut,,,,,,
1,3.45,3.45,0.00,0.00,0.00,6.90
2,20.69,15.52,5.17,1.72,3.45,46.55
3,15.52,20.69,1.72,0.00,0.00,37.93
4,3.45,1.72,0.00,0.00,0.00,5.17
5,1.72,1.72,0.00,0.00,0.00,3.45
All,44.83,43.10,6.90,1.72,3.45,100.00

Polaritätsprofil S2.1: modern/traditionell,1,2,3,4,5,All
Polaritätsprofil S2.1: leise/laut,,,,,,
1,3.45,0.00,0.00,0.00,3.45,6.90
2,1.72,12.07,13.79,15.52,3.45,46.55
3,3.45,12.07,15.52,6.90,0.00,37.93
4,0.00,1.72,0.00,0.00,3.45,5.17
5,0.00,0.00,1.72,0.00,1.72,3.45
All,8.62,25.86,31.03,22.41,12.07,100.00

Polaritätsprofil S2.1: gewagt/bodenständig    2      3      4      5     All
Polaritätsprofil S2.1: leise/laut
1                                           0.0   0.00   1.72   5.17    6.90
2                                           6.9   3.45  22.41  13.79   46.55
3                                           0.0  10.34  15.52  12.07   37.93
4                                           0.0   0.00   1.72   3.45    5.17
5                                           0.0   0.00   0.00   3.45    3.45
All                                         6.9  13.79  41.38  37.93  100.00

Polaritätsprofil S2.1: ruhig/temperamentvoll,1,2,3,4,All
Polaritätsprofil S2.1: leise/laut,,,,,
1,6.90,0.00,0.00,0.00,6.90
2,22.41,13.79,3.45,6.90,46.55
3,12.07,13.79,10.34,1.72,37.93
4,3.45,1.72,0.00,0.00,5.17
5,1.72,0.00,1.72,0.00,3.45
All,46.55,29.31,15.52,8.62,100.00

Polaritätsprofil S2.1: einfühlsam/unsensibel      1      2     3     4     All
Polaritätsprofil S2.1: leise/laut
1                                              5.17   1.72  0.00  0.00    6.90
2                                             17.24  22.41  5.17  1.72   46.55
3                                             10.34  27.59  0.00  0.00   37.93
4                                              0.00   5.17  0.00  0.00    5.17
5                                              0.00   0.00  1.72  1.72    3.45
All                                           32.76  56.90  6.90  3.45  100.00

Sprecher S2.2

Polaritätsprofil S2.2: aufrichtig/unaufrichtig,1,2,3,4,5,All
Polaritätsprofil S2.2: leise/laut,,,,,,
1,1.72,0.00,0.00,0.00,0.00,1.72
2,0.00,6.90,3.45,1.72,0.00,12.07
3,6.90,18.97,13.79,10.34,0.00,50.00
4,6.90,13.79,6.90,5.17,0.00,32.76
5,0.00,1.72,0.00,0.00,1.72,3.45
All,15.52,41.38,24.14,17.24,1.72,100.00

Polaritätsprofil S2.2: modern/traditionell,1,2,3,4,5,All
Polaritätsprofil S2.2: leise/laut,,,,,,
1,0.00,0.00,0.00,0.00,1.72,1.72
2,0.00,1.72,0.00,8.62,1.72,12.07
3,1.72,5.17,24.14,17.24,1.72,50.00
4,0.00,6.90,6.90,15.52,3.45,32.76
5,0.00,1.72,0.00,0.00,1.72,3.45
All,1.72,15.52,31.03,41.38,10.34,100.00

Polaritätsprofil S2.2: gewagt/bodenständig      2      3      4      5     All
Polaritätsprofil S2.2: leise/laut
1                                            0.00   0.00   0.00   1.72    1.72
2                                            0.00   5.17   5.17   1.72   12.07
3                                            3.45  17.24  20.69   8.62   50.00
4                                            6.90   8.62  10.34   6.90   32.76
5                                            0.00   0.00   1.72   1.72    3.45
All                                         10.34  31.03  37.93  20.69  100.00

Polaritätsprofil S2.2: ruhig/temperamentvoll,1,2,3,4,5,All
Polaritätsprofil S2.2: leise/laut,,,,,,
1,1.72,0.00,0.00,0.00,0.00,1.72
2,1.72,8.62,1.72,0.00,0.00,12.07
3,3.45,18.97,15.52,10.34,1.72,50.00
4,1.72,8.62,3.45,18.97,0.00,32.76
5,1.72,1.72,0.00,0.00,0.00,3.45
All,10.34,37.93,20.69,29.31,1.72,100.00

Polaritätsprofil S2.2: einfühlsam/unsensibel,1,2,3,4,All
Polaritätsprofil S2.2: leise/laut,,,,,
1,1.72,0.00,0.00,0.00,1.72
2,1.72,3.45,3.45,3.45,12.07
3,3.45,13.79,24.14,8.62,50.00
4,5.17,10.34,12.07,5.17,32.76
5,0.00,3.45,0.00,0.00,3.45
All,12.07,31.03,39.66,17.24,100.00

Sprecher S3.1

Polaritätsprofil S3.1: aufrichtig/unaufrichtig,1,2,3,4,5,All
Polaritätsprofil S3.1: leise/laut,,,,,,
1,0.00,0.00,1.72,3.45,1.72,6.90
2,0.00,8.62,8.62,6.90,12.07,36.21
3,1.72,1.72,17.24,15.52,5.17,41.38
4,0.00,0.00,6.90,1.72,1.72,10.34
5,0.00,0.00,0.00,1.72,3.45,5.17
All,1.72,10.34,34.48,29.31,24.14,100.00

Polaritätsprofil S3.1: modern/traditionell,1,2,3,4,5,All
Polaritätsprofil S3.1: leise/laut,,,,,,
1,0.00,0.00,1.72,3.45,1.72,6.90
2,1.72,5.17,13.79,8.62,6.90,36.21
3,0.00,5.17,13.79,18.97,3.45,41.38
4,0.00,1.72,1.72,5.17,1.72,10.34
5,3.45,0.00,0.00,1.72,0.00,5.17
All,5.17,12.07,31.03,37.93,13.79,100.00

Polaritätsprofil S3.1: gewagt/bodenständig      2      3      4      5     All
Polaritätsprofil S3.1: leise/laut
1                                            0.00   1.72   0.00   5.17    6.90
2                                            1.72   8.62  20.69   5.17   36.21
3                                            5.17  15.52  17.24   3.45   41.38
4                                            1.72   3.45   1.72   3.45   10.34
5                                            1.72   1.72   0.00   1.72    5.17
All                                         10.34  31.03  39.66  18.97  100.00

Polaritätsprofil S3.1: ruhig/temperamentvoll,1,2,3,4,5,All
Polaritätsprofil S3.1: leise/laut,,,,,,
1,5.17,0.00,1.72,0.00,0.00,6.90
2,15.52,15.52,5.17,0.00,0.00,36.21
3,13.79,13.79,10.34,3.45,0.00,41.38
4,3.45,3.45,1.72,1.72,0.00,10.34
5,1.72,0.00,0.00,1.72,1.72,5.17
All,39.66,32.76,18.97,6.90,1.72,100.00

Polaritätsprofil S3.1: einfühlsam/unsensibel,1,2,3,4,5,All
Polaritätsprofil S3.1: leise/laut,,,,,,
1,1.72,1.72,0.00,1.72,1.72,6.90
2,5.17,17.24,5.17,5.17,3.45,36.21
3,3.45,8.62,18.97,8.62,1.72,41.38
4,0.00,0.00,5.17,3.45,1.72,10.34
5,0.00,1.72,0.00,0.00,3.45,5.17
All,10.34,29.31,29.31,18.97,12.07,100.00

Sprecher S3.2

Polaritätsprofil S3.2: aufrichtig/unaufrichtig,1,2,3,4,5,All
Polaritätsprofil S3.2: leise/laut,,,,,,
1,0.00,0.00,0.00,0.00,1.72,1.72
2,0.00,1.72,3.45,8.62,3.45,17.24
3,0.00,3.45,13.79,24.14,3.45,44.83
4,0.00,6.90,12.07,12.07,1.72,32.76
5,1.72,0.00,0.00,0.00,1.72,3.45
All,1.72,12.07,29.31,44.83,12.07,100.00

Polaritätsprofil S3.2: modern/traditionell,1,2,3,4,5,All
Polaritätsprofil S3.2: leise/laut,,,,,,
1,0.00,0.00,0.00,0.00,1.72,1.72
2,1.72,8.62,5.17,1.72,0.00,17.24
3,0.00,10.34,22.41,10.34,1.72,44.83
4,1.72,6.90,10.34,13.79,0.00,32.76
5,1.72,0.00,0.00,0.00,1.72,3.45
All,5.17,25.86,37.93,25.86,5.17,100.00

Polaritätsprofil S3.2: gewagt/bodenständig,1,2,3,4,5,All
Polaritätsprofil S3.2: leise/laut,,,,,,
1,0.00,0.00,0.00,0.00,1.72,1.72
2,1.72,6.90,6.90,0.00,1.72,17.24
3,0.00,5.17,20.69,13.79,5.17,44.83
4,0.00,8.62,10.34,12.07,1.72,32.76
5,1.72,0.00,0.00,0.00,1.72,3.45
All,3.45,20.69,37.93,25.86,12.07,100.00

Polaritätsprofil S3.2: ruhig/temperamentvoll,1,2,3,4,5,All
Polaritätsprofil S3.2: leise/laut,,,,,,
1,1.72,0.00,0.00,0.00,0.00,1.72
2,1.72,5.17,5.17,5.17,0.00,17.24
3,3.45,13.79,18.97,8.62,0.00,44.83
4,1.72,12.07,10.34,8.62,0.00,32.76
5,0.00,0.00,1.72,0.00,1.72,3.45
All,8.62,31.03,36.21,22.41,1.72,100.00

Polaritätsprofil S3.2: einfühlsam/unsensibel,1,2,3,4,5,All
Polaritätsprofil S3.2: leise/laut,,,,,,
1,0.00,0.00,0.00,0.00,1.72,1.72
2,0.00,3.45,3.45,6.90,3.45,17.24
3,0.00,8.62,13.79,18.97,3.45,44.83
4,0.00,3.45,15.52,10.34,3.45,32.76
5,1.72,0.00,0.00,0.00,1.72,3.45
All,1.72,15.52,32.76,36.21,13.79,100.00

Sprecher S4.1

Polaritätsprofil S4.1: aufrichtig/unaufrichtig,1,2,3,4,5,All
Polaritätsprofil S4.1: leise/laut,,,,,,
1,1.72,1.72,0.00,0.00,5.17,8.62
2,3.45,10.34,6.90,10.34,6.90,37.93
3,3.45,17.24,10.34,13.79,1.72,46.55
4,0.00,1.72,5.17,0.00,0.00,6.90
All,8.62,31.03,22.41,24.14,13.79,100.00

Polaritätsprofil S4.1: modern/traditionell,1,2,3,4,5,All
Polaritätsprofil S4.1: leise/laut,,,,,,
1,0.00,1.72,1.72,1.72,3.45,8.62
2,0.00,12.07,10.34,13.79,1.72,37.93
3,5.17,8.62,17.24,13.79,1.72,46.55
4,0.00,0.00,5.17,1.72,0.00,6.90
All,5.17,22.41,34.48,31.03,6.90,100.00

Polaritätsprofil S4.1: gewagt/bodenständig,1,2,3,4,5,All
Polaritätsprofil S4.1: leise/laut,,,,,,
1,0.00,0.00,1.72,5.17,1.72,8.62
2,0.00,1.72,8.62,24.14,3.45,37.93
3,1.72,3.45,18.97,12.07,10.34,46.55
4,0.00,0.00,1.72,5.17,0.00,6.90
All,1.72,5.17,31.03,46.55,15.52,100.00

Polaritätsprofil S4.1: ruhig/temperamentvoll,1,2,3,4,All
Polaritätsprofil S4.1: leise/laut,,,,,
1,5.17,3.45,0.00,0.00,8.62
2,18.97,17.24,0.00,1.72,37.93
3,8.62,20.69,12.07,5.17,46.55
4,0.00,5.17,1.72,0.00,6.90
All,32.76,46.55,13.79,6.90,100.00

Polaritätsprofil S4.1: einfühlsam/unsensibel,1,2,3,4,5,All
Polaritätsprofil S4.1: leise/laut,,,,,,
1,1.72,0.00,1.72,3.45,1.72,8.62
2,1.72,13.79,12.07,8.62,1.72,37.93
3,3.45,18.97,15.52,6.90,1.72,46.55
4,0.00,3.45,3.45,0.00,0.00,6.90
All,6.90,36.21,32.76,18.97,5.17,100.00

Sprecher S4.2

Polaritätsprofil S4.2: aufrichtig/unaufrichtig,1,2,3,4,5,All
Polaritätsprofil S4.2: leise/laut,,,,,,
1,1.72,0.00,0.00,0.00,1.72,3.45
2,0.00,0.00,1.72,0.00,0.00,1.72
3,1.72,13.79,13.79,8.62,3.45,41.38
4,0.00,10.34,18.97,17.24,1.72,48.28
5,0.00,0.00,1.72,1.72,1.72,5.17
All,3.45,24.14,36.21,27.59,8.62,100.00

Polaritätsprofil S4.2: modern/traditionell,1,2,3,4,5,All
Polaritätsprofil S4.2: leise/laut,,,,,,
1,1.72,0.00,0.00,0.00,1.72,3.45
2,0.00,1.72,0.00,0.00,0.00,1.72
3,1.72,20.69,13.79,5.17,0.00,41.38
4,6.90,20.69,10.34,10.34,0.00,48.28
5,1.72,1.72,1.72,0.00,0.00,5.17
All,12.07,44.83,25.86,15.52,1.72,100.00

Polaritätsprofil S4.2: gewagt/bodenständig,1,2,3,4,5,All
Polaritätsprofil S4.2: leise/laut,,,,,,
1,0.00,0.00,0.00,0.00,3.45,3.45
2,0.00,0.00,1.72,0.00,0.00,1.72
3,1.72,10.34,13.79,10.34,5.17,41.38
4,1.72,20.69,17.24,6.90,1.72,48.28
5,0.00,3.45,1.72,0.00,0.00,5.17
All,3.45,34.48,34.48,17.24,10.34,100.00

Polaritätsprofil S4.2: ruhig/temperamentvoll,1,2,3,4,5,All
Polaritätsprofil S4.2: leise/laut,,,,,,
1,3.45,0.00,0.00,0.00,0.00,3.45
2,0.00,0.00,1.72,0.00,0.00,1.72
3,1.72,12.07,5.17,22.41,0.00,41.38
4,0.00,3.45,6.90,29.31,8.62,48.28
5,0.00,0.00,0.00,5.17,0.00,5.17
All,5.17,15.52,13.79,56.90,8.62,100.00

Polaritätsprofil S4.2: einfühlsam/unsensibel,1,2,3,4,5,All
Polaritätsprofil S4.2: leise/laut,,,,,,
1,1.72,0.00,0.00,0.00,1.72,3.45
2,0.00,0.00,1.72,0.00,0.00,1.72
3,0.00,13.79,13.79,12.07,1.72,41.38
4,1.72,6.90,25.86,13.79,0.00,48.28
5,0.00,0.00,1.72,3.45,0.00,5.17
All,3.45,20.69,43.10,29.31,3.45,100.00

Sprecher S5.1

Polaritätsprofil S5.1: aufrichtig/unaufrichtig      1      2     3     All
Polaritätsprofil S5.1: leise/laut
1                                                8.62   0.00  0.00    8.62
2                                               18.97  20.69  3.45   43.10
3                                               18.97  22.41  3.45   44.83
4                                                1.72   1.72  0.00    3.45
All                                             48.28  44.83  6.90  100.00

Polaritätsprofil S5.1: modern/traditionell,1,2,3,4,5,All
Polaritätsprofil S5.1: leise/laut,,,,,,
1,3.45,1.72,1.72,1.72,0.00,8.62
2,3.45,12.07,12.07,8.62,6.90,43.10
3,6.90,8.62,15.52,8.62,5.17,44.83
4,1.72,0.00,1.72,0.00,0.00,3.45
All,15.52,22.41,31.03,18.97,12.07,100.00

Polaritätsprofil S5.1: gewagt/bodenständig,1,2,3,4,5,All
Polaritätsprofil S5.1: leise/laut,,,,,,
1,1.72,0.00,0.00,1.72,5.17,8.62
2,0.00,0.00,3.45,22.41,17.24,43.10
3,0.00,1.72,10.34,17.24,15.52,44.83
4,0.00,0.00,0.00,1.72,1.72,3.45
All,1.72,1.72,13.79,43.10,39.66,100.00

Polaritätsprofil S5.1: ruhig/temperamentvoll,1,2,3,4,5,All
Polaritätsprofil S5.1: leise/laut,,,,,,
1,6.90,1.72,0.00,0.00,0.00,8.62
2,17.24,18.97,5.17,0.00,1.72,43.10
3,15.52,20.69,3.45,5.17,0.00,44.83
4,1.72,1.72,0.00,0.00,0.00,3.45
All,41.38,43.10,8.62,5.17,1.72,100.00

Polaritätsprofil S5.1: einfühlsam/unsensibel,1,2,3,4,All
Polaritätsprofil S5.1: leise/laut,,,,,
1,8.62,0.00,0.00,0.00,8.62
2,22.41,12.07,8.62,0.00,43.10
3,15.52,22.41,3.45,3.45,44.83
4,1.72,1.72,0.00,0.00,3.45
All,48.28,36.21,12.07,3.45,100.00

Sprecher S5.2

Polaritätsprofil S5.2: aufrichtig/unaufrichtig,1,2,3,4,5,All
Polaritätsprofil S5.2: leise/laut,,,,,,
1,1.72,0.00,0.00,0.00,0.00,1.72
2,0.00,0.00,1.72,0.00,0.00,1.72
3,0.00,1.72,1.72,6.90,3.45,13.79
4,0.00,10.34,22.41,13.79,5.17,51.72
5,0.00,0.00,10.34,10.34,10.34,31.03
All,1.72,12.07,36.21,31.03,18.97,100.00

Polaritätsprofil S5.2: modern/traditionell,1,2,3,4,5,All
Polaritätsprofil S5.2: leise/laut,,,,,,
1,1.72,0.00,0.00,0.00,0.00,1.72
2,0.00,1.72,0.00,0.00,0.00,1.72
3,3.45,5.17,3.45,1.72,0.00,13.79
4,12.07,31.03,6.90,0.00,1.72,51.72
5,6.90,12.07,8.62,1.72,1.72,31.03
All,24.14,50.00,18.97,3.45,3.45,100.00

Polaritätsprofil S5.2: gewagt/bodenständig,1,2,3,4,5,All
Polaritätsprofil S5.2: leise/laut,,,,,,
1,0.00,0.00,0.00,0.00,1.72,1.72
2,0.00,1.72,0.00,0.00,0.00,1.72
3,1.72,5.17,1.72,5.17,0.00,13.79
4,10.34,27.59,6.90,3.45,3.45,51.72
5,12.07,10.34,6.90,0.00,1.72,31.03
All,24.14,44.83,15.52,8.62,6.90,100.00

Polaritätsprofil S5.2: ruhig/temperamentvoll     1     3      4      5     All
Polaritätsprofil S5.2: leise/laut
1                                             1.72  0.00   0.00   0.00    1.72
2                                             0.00  0.00   1.72   0.00    1.72
3                                             0.00  1.72   8.62   3.45   13.79
4                                             0.00  0.00  29.31  22.41   51.72
5                                             0.00  1.72  13.79  15.52   31.03
All                                           1.72  3.45  53.45  41.38  100.00

Polaritätsprofil S5.2: einfühlsam/unsensibel,1,2,3,4,5,All
Polaritätsprofil S5.2: leise/laut,,,,,,
1,1.72,0.00,0.00,0.00,0.00,1.72
2,0.00,0.00,1.72,0.00,0.00,1.72
3,0.00,1.72,1.72,10.34,0.00,13.79
4,0.00,1.72,13.79,31.03,5.17,51.72
5,0.00,0.00,3.45,8.62,18.97,31.03
All,1.72,3.45,20.69,50.00,24.14,100.00

Sprecher S6.1

Polaritätsprofil S6.1: aufrichtig/unaufrichtig,1,2,3,4,5,All
Polaritätsprofil S6.1: leise/laut,,,,,,
1,1.72,3.45,0.00,1.72,3.45,10.34
2,3.45,17.24,10.34,8.62,1.72,41.38
3,5.17,10.34,10.34,6.90,6.90,39.66
4,0.00,3.45,0.00,1.72,1.72,6.90
5,1.72,0.00,0.00,0.00,0.00,1.72
All,12.07,34.48,20.69,18.97,13.79,100.00

Polaritätsprofil S6.1: modern/traditionell,1,2,3,4,5,All
Polaritätsprofil S6.1: leise/laut,,,,,,
1,0.00,1.72,0.00,3.45,5.17,10.34
2,0.00,0.00,12.07,17.24,12.07,41.38
3,0.00,1.72,10.34,13.79,13.79,39.66
4,0.00,0.00,0.00,6.90,0.00,6.90
5,1.72,0.00,0.00,0.00,0.00,1.72
All,1.72,3.45,22.41,41.38,31.03,100.00

Polaritätsprofil S6.1: gewagt/bodenständig      3      4      5     All
Polaritätsprofil S6.1: leise/laut
1                                            1.72   1.72   6.90   10.34
2                                            6.90  18.97  15.52   41.38
3                                            3.45  10.34  25.86   39.66
4                                            0.00   3.45   3.45    6.90
5                                            0.00   0.00   1.72    1.72
All                                         12.07  34.48  53.45  100.00

Polaritätsprofil S6.1: ruhig/temperamentvoll      1      2      3     All
Polaritätsprofil S6.1: leise/laut
1                                              6.90   1.72   1.72   10.34
2                                             20.69  18.97   1.72   41.38
3                                             17.24  15.52   6.90   39.66
4                                              3.45   3.45   0.00    6.90
5                                              1.72   0.00   0.00    1.72
All                                           50.00  39.66  10.34  100.00

Polaritätsprofil S6.1: einfühlsam/unsensibel,1,2,3,4,5,All
Polaritätsprofil S6.1: leise/laut,,,,,,
1,3.45,1.72,1.72,0.00,3.45,10.34
2,1.72,12.07,17.24,8.62,1.72,41.38
3,5.17,6.90,13.79,3.45,10.34,39.66
4,0.00,1.72,1.72,3.45,0.00,6.90
5,1.72,0.00,0.00,0.00,0.00,1.72
All,12.07,22.41,34.48,15.52,15.52,100.00

Sprecher S6.2

Polaritätsprofil S6.2: aufrichtig/unaufrichtig,1,2,3,4,5,All
Polaritätsprofil S6.2: leise/laut,,,,,,
3,0.00,0.00,1.72,12.07,1.72,15.52
4,3.45,3.45,8.62,15.52,8.62,39.66
5,1.72,5.17,6.90,17.24,13.79,44.83
All,5.17,8.62,17.24,44.83,24.14,100.00

Polaritätsprofil S6.2: modern/traditionell,1,2,3,4,5,All
Polaritätsprofil S6.2: leise/laut,,,,,,
3,1.72,5.17,3.45,5.17,0.00,15.52
4,5.17,6.90,15.52,6.90,5.17,39.66
5,6.90,10.34,17.24,5.17,5.17,44.83
All,13.79,22.41,36.21,17.24,10.34,100.00

Polaritätsprofil S6.2: gewagt/bodenständig,1,2,3,4,5,All
Polaritätsprofil S6.2: leise/laut,,,,,,
3,3.45,1.72,6.90,1.72,1.72,15.52
4,10.34,12.07,5.17,6.90,5.17,39.66
5,13.79,17.24,10.34,0.00,3.45,44.83
All,27.59,31.03,22.41,8.62,10.34,100.00

Polaritätsprofil S6.2: ruhig/temperamentvoll,1,2,3,4,5,All
Polaritätsprofil S6.2: leise/laut,,,,,,
3,0.00,1.72,6.90,5.17,1.72,15.52
4,1.72,5.17,5.17,17.24,10.34,39.66
5,0.00,0.00,0.00,22.41,22.41,44.83
All,1.72,6.90,12.07,44.83,34.48,100.00

Polaritätsprofil S6.2: einfühlsam/unsensibel,1,2,3,4,5,All
Polaritätsprofil S6.2: leise/laut,,,,,,
3,0.00,0.00,1.72,6.90,6.90,15.52
4,0.00,3.45,5.17,17.24,13.79,39.66
5,1.72,0.00,3.45,15.52,24.14,44.83
All,1.72,3.45,10.34,39.66,44.83,100.00

Sprecher S7.1

Polaritätsprofil S7.1: aufrichtig/unaufrichtig,1,2,3,4,5,All
Polaritätsprofil S7.1: leise/laut,,,,,,
1,5.17,5.17,0.00,0.00,1.72,12.07
2,5.17,20.69,13.79,1.72,0.00,41.38
3,3.45,13.79,10.34,6.90,1.72,36.21
4,3.45,1.72,1.72,1.72,0.00,8.62
5,1.72,0.00,0.00,0.00,0.00,1.72
All,18.97,41.38,25.86,10.34,3.45,100.00

Polaritätsprofil S7.1: modern/traditionell     1      3      4      5     All
Polaritätsprofil S7.1: leise/laut
1                                           0.00   0.00   1.72  10.34   12.07
2                                           0.00   6.90  15.52  18.97   41.38
3                                           0.00   8.62  12.07  15.52   36.21
4                                           0.00   1.72   1.72   5.17    8.62
5                                           1.72   0.00   0.00   0.00    1.72
All                                         1.72  17.24  31.03  50.00  100.00

Polaritätsprofil S7.1: gewagt/bodenständig,1,2,3,4,5,All
Polaritätsprofil S7.1: leise/laut,,,,,,
1,0.00,0.00,0.00,5.17,6.90,12.07
2,0.00,1.72,5.17,15.52,18.97,41.38
3,1.72,0.00,10.34,8.62,15.52,36.21
4,0.00,0.00,1.72,6.90,0.00,8.62
5,0.00,0.00,0.00,0.00,1.72,1.72
All,1.72,1.72,17.24,36.21,43.10,100.00

Polaritätsprofil S7.1: ruhig/temperamentvoll      1      2     3     All
Polaritätsprofil S7.1: leise/laut
1                                              8.62   3.45  0.00   12.07
2                                             17.24  20.69  3.45   41.38
3                                             22.41  13.79  0.00   36.21
4                                              3.45   3.45  1.72    8.62
5                                              1.72   0.00  0.00    1.72
All                                           53.45  41.38  5.17  100.00

Polaritätsprofil S7.1: einfühlsam/unsensibel,1,2,3,4,5,All
Polaritätsprofil S7.1: leise/laut,,,,,,
1,5.17,3.45,0.00,1.72,1.72,12.07
2,6.90,24.14,5.17,5.17,0.00,41.38
3,3.45,17.24,10.34,1.72,3.45,36.21
4,1.72,1.72,3.45,1.72,0.00,8.62
5,1.72,0.00,0.00,0.00,0.00,1.72
All,18.97,46.55,18.97,10.34,5.17,100.00

Sprecher S7.2

Polaritätsprofil S7.2: aufrichtig/unaufrichtig,1,2,3,4,5,All
Polaritätsprofil S7.2: leise/laut,,,,,,
3,0.00,0.00,0.00,5.17,1.72,6.90
4,1.72,6.90,10.34,5.17,15.52,39.66
5,0.00,6.90,12.07,20.69,13.79,53.45
All,1.72,13.79,22.41,31.03,31.03,100.00

Polaritätsprofil S7.2: modern/traditionell,1,2,3,4,5,All
Polaritätsprofil S7.2: leise/laut,,,,,,
3,0.00,6.90,0.00,0.00,0.00,6.90
4,3.45,12.07,12.07,8.62,3.45,39.66
5,8.62,13.79,13.79,6.90,10.34,53.45
All,12.07,32.76,25.86,15.52,13.79,100.00

Polaritätsprofil S7.2: gewagt/bodenständig,1,2,3,4,5,All
Polaritätsprofil S7.2: leise/laut,,,,,,
3,0.00,6.90,0.00,0.00,0.00,6.90
4,13.79,20.69,5.17,0.00,0.00,39.66
5,18.97,20.69,10.34,1.72,1.72,53.45
All,32.76,48.28,15.52,1.72,1.72,100.00

Polaritätsprofil S7.2: ruhig/temperamentvoll     3      4      5     All
Polaritätsprofil S7.2: leise/laut
3                                             0.00   5.17   1.72    6.90
4                                             1.72  24.14  13.79   39.66
5                                             3.45  20.69  29.31   53.45
All                                           5.17  50.00  44.83  100.00

Polaritätsprofil S7.2: einfühlsam/unsensibel,2,3,4,5,All
Polaritätsprofil S7.2: leise/laut,,,,,
3,0.00,3.45,3.45,0.00,6.90
4,3.45,10.34,17.24,8.62,39.66
5,1.72,12.07,22.41,17.24,53.45
All,5.17,25.86,43.10,25.86,100.00